name: Build Action

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 4.7.2
        cache: true
    - name: Dependencies
      run: dotnet restore --locked-mode ./PatternsMaker/PatternsMaker.sln

    - name: Execute dotnet
        run: dotnet build ./PatternsMaker/PatternsMaker.sln